modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "generations_ultraspace"
version = "${version}"
displayName = "Generations Ultraspace"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.generations_ultraspace]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generations_ultraspace]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"
