modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/GenerationsMod/Generations-UltraSpace.git"
license = "Insert License Here"

[[mods]]
modId = "generations_ultraspace"
version = "${version}"
displayName = "Generations Ultraspace"
authors = "The Generations Team"
description = '''
Ultra Space Dimension Module for Generations.
'''
#logoFile = ""

[[dependencies.generations_ultraspace]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generations_ultraspace]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.generations_ultraspace]]
modId = "generations_core"
mandatory = true
ordering = "BEFORE"
side = "BOTH"
